# Generated by Django 6.0.2 on 2026-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='category',
            field=models.CharField(choices=[('tilshunoslik', 'Tilshunoslik'), ('leksikologiya', 'Leksikologiya'), ('sintaksis', 'Sintaksis'), ('fonetika', 'Fonetika')], default='tilshunoslik', help_text='Maqola turkumini tanlang', max_length=50, verbose_name='Turkum'),
        ),
    ]
