# Generated by Django 6.0.2 on 2026-02-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maqola_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqola',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='maqola',
            name='abstract',
            field=models.TextField(blank=True, help_text='Avtomatik yaratiladi (tahrirlashingiz mumkin)', null=True, verbose_name='Annotatsiya'),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='keywords',
            field=models.CharField(blank=True, help_text='Avtomatik ajratiladi (tahrirlashingiz mumkin)', max_length=500, null=True, verbose_name="Kalit so'zlar"),
        ),
    ]
