# Generated by Django 6.0.2 on 2026-02-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_maqola_cover_image_alter_maqola_abstract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqola',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='volume',
        ),
    ]
