# Generated by Django 6.0.2 on 2026-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_maqola_abstract_remove_maqola_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='table_of_contents',
        ),
        migrations.AlterField(
            model_name='maqola',
            name='journal',
            field=models.CharField(help_text='Qaysi jurnalda yoki nashrda chop etilgan', max_length=300, verbose_name='Manba'),
        ),
    ]
