# Generated by Django 6.0.2 on 2026-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_kitob_table_of_contents_alter_maqola_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shogird',
            name='total_characters',
        ),
        migrations.RemoveField(
            model_name='shogird',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='shogird',
            name='total_words',
        ),
        migrations.AlterField(
            model_name='shogird',
            name='achievements',
            field=models.TextField(blank=True, help_text="Har bir yutuqni vergul bilan ajrating. Masalan: 15+ ilmiy maqola, 2 ta monografiya, O'qituvchi-mentor", null=True, verbose_name='Asosiy yutuqlar'),
        ),
    ]
