# Generated by Django 6.0.2 on 2026-02-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_shogird_total_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogalereya',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fotogalereya',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='fotogalereya',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', help_text="To'liq YouTube video linki. Masalan: https://www.youtube.com/watch?v=jNQXAC9IVRw", max_length=500, verbose_name='YouTube link'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('lectures', "Ma'ruzalar"), ('lessons', 'Darsliklar'), ('interviews', 'Suhbatlar')], default='lectures', max_length=20, verbose_name='Turkum'),
        ),
    ]
