# Generated by Django 6.0.2 on 2026-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_fotogalereya_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='category',
            field=models.CharField(choices=[('tilshunoslik', 'Tilshunoslik'), ('leksikologiya', 'Leksikologiya'), ('sintaksis', 'Sintaksis'), ('fonetika', 'Fonetika'), ('ustoz_haqida', 'Ustoz haqida (maxsus)')], default='tilshunoslik', help_text='Maqola turkumini tanlang', max_length=50, verbose_name='Turkum'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('lectures', "Ma'ruzalar"), ('lessons', 'Darsliklar'), ('interviews', 'Suhbatlar'), ('ustoz_haqida', 'Ustoz haqida (maxsus)')], default='lectures', max_length=20, verbose_name='Turkum'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(help_text="To'liq YouTube video linki. Masalan: https://www.youtube.com/watch?v=jNQXAC9IVRw", max_length=500, verbose_name='YouTube link'),
        ),
    ]
