# Generated by Django 6.0.2 on 2026-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_maqola_category_alter_video_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shogird',
            name='tartib',
            field=models.IntegerField(default=0, help_text="Sahifada ko'rsatish tartibi (kichik raqam birinchi)", verbose_name='Tartib raqami'),
        ),
    ]
