# Generated by Django 6.0.2 on 2026-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_shogird_tartib'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='tartib',
            field=models.IntegerField(default=0, help_text="Sahifada ko'rsatish tartibi (kichik raqam birinchi)", verbose_name='Tartib raqami'),
        ),
    ]
