# Generated by Django 6.0.2 on 2026-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_maqola_tartib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='category',
            field=models.CharField(choices=[('uslubshunoslik', 'Uslubshunoslik va nutq madaniyati'), ('onomastika', 'Onomastika va antroponimika'), ('matn_lingvistikasi', 'Matn lingvistikasi'), ('alisher_navoiy', 'Alisher Navoiy ijodi'), ('fonetika', 'Fonetika va fonologiya'), ('ustoz_haqida', 'Ustoz haqida (maxsus)')], default='tilshunoslik', help_text='Maqola turkumini tanlang', max_length=50, verbose_name='Turkum'),
        ),
    ]
