# Generated by Django 6.0.2 on 2026-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_maqola_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xotira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Masalan: Birinchi ma'ruzam, Paris konferensiyasi", max_length=500, verbose_name='Xotira sarlavhasi')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL slug')),
                ('date', models.CharField(help_text='Masalan: 1995-yil may, 2008-yil oktabr', max_length=100, verbose_name='Sana')),
                ('year', models.IntegerField(help_text='Voqea yili (masalan: 1995)', verbose_name='Yil')),
                ('location', models.CharField(help_text='Masalan: Toshkent Davlat Universiteti, Samarqand', max_length=300, verbose_name='Joy')),
                ('full_text', models.TextField(help_text="Xotira haqida batafsil ma'lumot. HTML teglari ishlatilishi mumkin.", verbose_name="To'liq matn")),
                ('image', models.ImageField(blank=True, help_text="Xotira bilan bog'liq rasm (ixtiyoriy)", null=True, upload_to='images/xotiralar/', verbose_name='Rasm')),
                ('tags', models.CharField(blank=True, help_text='Teglarni vergul bilan ajrating: talim, aspirantura, maruzaq', max_length=500, verbose_name='Teglar')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Xotira',
                'verbose_name_plural': 'Xotiralar',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
