# Generated by Django 6.0.2 on 2026-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_xotira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xotira',
            options={'ordering': ['-year', '-id'], 'verbose_name': 'Xotira', 'verbose_name_plural': 'Xotiralar'},
        ),
        migrations.AddField(
            model_name='xotira',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='date',
            field=models.CharField(help_text="Masalan: '1982-yil 15-sentabr' yoki 'Kuz fasli, 1990-yil'", max_length=100, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='full_text',
            field=models.TextField(help_text='Xotira haqida batafsil hikoya. HTML taglar ishlatish mumkin (<p>, <strong>, <em>)', verbose_name="To'liq matn"),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='image',
            field=models.ImageField(blank=True, help_text='Voqeaga oid rasm (1200x800px tavsiya). Ixtiyoriy', null=True, upload_to='images/xotiralar/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Asosiy sahifada ko'rsatish uchun belgilash", verbose_name='Muhim xotira'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='location',
            field=models.CharField(help_text="Voqea sodir bo'lgan joy. Masalan: 'Toshkent Davlat Universiteti'", max_length=200, verbose_name='Joy'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='tags',
            field=models.CharField(blank=True, help_text="Vergul bilan ajratib yozing. Masalan: ta'lim, aspirantura, ma'ruza, birinchi kun", max_length=500, null=True, verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='title',
            field=models.CharField(help_text="Qisqa va mazmunli sarlavha. Masalan: 'Birinchi ma'ruzam'", max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='xotira',
            name='year',
            field=models.IntegerField(help_text='Asosiy yil (tartibga solish uchun). Masalan: 1982', verbose_name='Yil'),
        ),
    ]
