# Generated by Django 6.0.2 on 2026-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_maqola_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='category',
            field=models.CharField(choices=[('uslubshunoslik', 'Uslubshunoslik va nutq madaniyati'), ('matn_lingvistikasi', 'Matn lingvistikasi'), ('alisher_navoiy', 'Alisher Navoiy ijodi'), ('fonetika', 'Fonetika va fonologiya'), ('sadriddin_ayniy', 'Sadriddin Ayniy maqolalari'), ('leksikologiya', 'Leksikologiya'), ('ustoz_haqida', 'Ustoz haqida (maxsus)')], default='uslubshunoslik', help_text='Maqola turkumini tanlang', max_length=50, verbose_name='Turkum'),
        ),
    ]
