# Generated by Django 5.2.11 on 2026-03-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_maqola_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotogalereya',
            name='image',
            field=models.ImageField(blank=True, help_text="Professional sifatli rasm (tavsiya: 1200x800px). Agar qo'shimcha rasmlar qo'shsangiz, bu maydon ixtiyoriy.", null=True, upload_to='images/fotogalereya/', verbose_name='Asosiy rasm (ixtiyoriy)'),
        ),
        migrations.CreateModel(
            name='FotogalereyaRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Professional sifatli rasm (tavsiya: 1200x800px)', upload_to='images/fotogalereya/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, help_text='Rasm haqida qisqacha izoh (ixtiyoriy)', max_length=500, verbose_name='Izoh')),
                ('order', models.IntegerField(default=0, help_text="Rasmlarni ko'rsatish tartibi (kichik raqam birinchi)", verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('fotogalereya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='main.fotogalereya', verbose_name='Fotogalereya')),
            ],
            options={
                'verbose_name': 'Fotogalereya rasmi',
                'verbose_name_plural': 'Fotogalereya rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
